//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2ZSuntours.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class A2ZDbModels : DbContext
    {
        public A2ZDbModels()
            : base("name=A2ZDbModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactUsForm> ContactUsForms { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<TripCustomer> TripCustomers { get; set; }
        public virtual DbSet<TripRequest> TripRequests { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripsPerReq> TripsPerReqs { get; set; }
    }
}
