//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2ZSuntours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripCustomer()
        {
            this.TripRequests = new HashSet<TripRequest>();
        }
    
        public int TripCustID { get; set; }
        public string TFirstName { get; set; }
        public string TLastName { get; set; }
        public string TEmail { get; set; }
        public string TCity { get; set; }
        public string TState { get; set; }
        public string TCountry { get; set; }
        public string TPhoneNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripRequest> TripRequests { get; set; }
    }
}
