//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2ZSuntours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripRequest()
        {
            this.TripsPerReqs = new HashSet<TripsPerReq>();
        }
    
        public int TripReqID { get; set; }
        public Nullable<int> TripCustID { get; set; }
        public Nullable<int> TripID { get; set; }
    
        public virtual TripCustomer TripCustomer { get; set; }
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripsPerReq> TripsPerReqs { get; set; }
    }
}
